name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancer les Tests
        working-directory: src
        run: | 
          python -m pytest 

deploy:
  runs-on: ubuntu-latest
  needs: test
  steps:
    - name: Deploiment sur la VM
      uses: appleboy/ssh-action@v0.1.6
      with: 
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd log430-a25-labo0
          git pull origin main
          pip install -r requirements.txt
          systemctl restart calculator.py

